name: build

on:
  push:
    paths:
      - 'char_data/**'
  workflow_dispatch:

jobs:
  update:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: disable auto crlf
        uses: steve02081504/disable-autocrlf@v1
        with:
          fuck-auto-CRLF: true
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: |
          npm install
          npm run build default "" ${{github.sha}}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./build
